### ISSUE TITLE
Enhancement - Settings -> add coin real estate 

### ISSUE THREAD

**Issue by jdmarlow86** [hyperdexapp/hyperdex#399]
With the Settings screen locked, with no scroll, adding a coin has a limited viewable drop-down. Suggest a way to make this drop-down more visible (maybe display on the right side of the drop-down selection).

Version: alpha 8
OS: win 10
Errors: None
Severity: Low (3)

![image](https://user-images.githubusercontent.com/22251770/42177944-956bf00e-7dfc-11e8-8ece-0124ecebd872.png)

**Comment by lukechilds** [comment]
Yeah, we struggled a bit with how to display this info, we tried a few different ways before settling on this. The settings view isn't finished btw, there will be more options going in here, so we need to be careful how much space each item takes up. having a huge list of all coins would make navigating the settings quite annoying.

Are you aware you can scroll through the dropdown, and also search via ticker or name. I think this is a good compromise of allowing users to very quickly enable a specific coin, or scroll and browse.

![kapture 2018-07-03 at 8 11 56](https://user-images.githubusercontent.com/2123375/42193532-21ec4e38-7e99-11e8-81b9-21f6a3012ba7.gif)

I'm not too sure what you mean by moving to the right side of the dropdown. If you think you've thought of a more user friendly way of displaying this data, we're definitely open to it.

**Comment by sindresorhus** [comment]
@lukechilds I think you're misunderstanding the issue. I'm pretty sure he means that the dropdown is cut-off prematurely (note the red box).
