### ISSUE TITLE
ZILLA - Settings ->Add coin

### ISSUE THREAD

**Issue by jdmarlow86** [hyperdexapp/hyperdex#414]
The only way to add ZILLA in the Settings is to type in the coin. It does not appear in the regular drop down.

Version: alpha 9
OS: win 10
Errors: none
Severity: Medium (2)

![image](https://user-images.githubusercontent.com/22251770/42521360-9f486eaa-8436-11e8-96c9-4e2bc52f590f.png)

**Comment by sindresorhus** [comment]
Thanks for reporting. This was just because we don't have any scrolling in the preferences so the dropdown with ChainZilla was cut-off and displayed ChainZilla outside the visible view. Should be fixed now.
